# Meshtastic Base Station Configuration

# Environment (development, testing, production)
environment: production  # Changed to production for Raspberry Pi 5 deployment

# Data retention in days
data_retention_days: 30

# Redis configuration
redis:
  host: pironman5.local  # Local Redis server on Raspberry Pi 5
  port: 6379
  password: null  # Set if using Redis authentication
  db: 0
  decode_responses: true

# Device configuration
device:
  port: /dev/ttyACM0  # Linux default for Meshtastic devices
  baud_rate: 115200
  timeout: 1.0

# Logging configuration
log_cfg:
  level: INFO
  file: meshtastic.log
  use_threshold: false
  debugging: false
  format: "%(asctime)s %(levelname)s:%(name)s:%(message)s"
