# Meshtastic Base Station Configuration

# Environment (development, testing, production)
environment: development

# Data retention in days
data_retention_days: 30

# Redis configuration
redis:
  host: pironman5.local  # Remote Redis server
  port: 6379
  password: null  # Set if using Redis authentication
  db: 0
  decode_responses: true

# Device configuration
device:
  port: COM3  # Windows COM port
  baud_rate: 115200
  timeout: 1.0

# Logging configuration
logging:
  level: INFO
  file: meshtastic.log
  use_threshold: false
  debugging: false
  format: "%(asctime)s %(levelname)s:%(name)s:%(message)s"